### ISSUE TITLE
Magento error after Ratepay installation

### ISSUE THREAD

**Issue by info2riaz** [ratepay/magento2-module#54]
**_Copy all files into app/code/ of your shop directory. Afterwords, choose one of the following options._** May I know which files I need to copy . 

After following the steps mentioned in https://ratepay.gitbook.io/magento2/get-started/installation am not able to run the magento project itself . before ratepay instllation the project was working fine . But after trying this plugin installation the project is not running and am getting the below error in log
_[2021-01-25 10:27:11] main.ERROR: Unable to resolve the source file for 'frontend/_view/en_US/Magento_Theme/favicon.ico' [] []
[2021-01-25 10:27:11] main.CRITICAL: Unable to resolve the source file for 'frontend/_view/en_US/Magento_Theme/favicon.ico' [] []_

**Comment by MartinKuhl** [comment]
Hi, please remove the file from app/code/ and try to install our module via composer https://ratepay.gitbook.io/magento2/get-started/installation#option-1-terminal
